# Generated by Django 5.0.7 on 2024-07-16 19:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="id",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=256, verbose_name="full name"),
                ),
                ("email", models.EmailField(max_length=256, verbose_name="email")),
                ("comment", models.TextField(verbose_name="comment")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
            ],
            options={
                "verbose_name": "review",
                "verbose_name_plural": "reviews",
                "db_table": "reviews",
                "ordering": ("-created_at",),
            },
        ),
    ]
